version: '3.8'

services:
  # MongoDB 服务
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "${DOCKER_MONGODB_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - tf_network

  # 后端服务
  backend:
    build: ./backend
    restart: always
    depends_on:
      - mongodb
    env_file:
      - .env
    ports:
      - "${DOCKER_BACKEND_PORT}:${PORT}"
    networks:
      - tf_network

  # 前端服务
  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - "${DOCKER_FRONTEND_PORT}:80"
    networks:
      - tf_network

networks:
  tf_network:
    driver: bridge

volumes:
  mongodb_data: 