version: '3.8'

services:
  # MongoDB 服务
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - tf_network

  # 后端服务
  backend:
    build: ./backend
    restart: always
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/trackflow
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=7d
      - CORS_ORIGIN=http://localhost:2455
    networks:
      - tf_network
    ports:
      - "3000:3000"

  # 前端服务
  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "2455:80"
    networks:
      - tf_network

networks:
  tf_network:
    driver: bridge

volumes:
  mongodb_data: 