version: '3.8'

services:
  # MongoDB 服务
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "${DOCKER_MONGODB_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - tf_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=password123

  # 后端服务
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/trackflow?authSource=admin
    ports:
      - "${DOCKER_BACKEND_PORT}:${PORT}"
    networks:
      - tf_network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:${PORT}/api/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  # 前端服务
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${DOCKER_FRONTEND_PORT}:80"
    networks:
      - tf_network

networks:
  tf_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local 