name: Build/Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Clean install directories (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          if exist frontend\node_modules rmdir /s /q frontend\node_modules
          if exist electron\node_modules rmdir /s /q electron\node_modules
          if exist frontend\dist rmdir /s /q frontend\dist
          if exist electron\dist rmdir /s /q electron\dist
          if exist electron\release rmdir /s /q electron\release

      - name: Clean install directories (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          rm -rf frontend/node_modules electron/node_modules frontend/dist electron/dist electron/release || true
          
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install
          npm install @tailwindcss/forms
          cd ../electron
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      - name: Debug Info
        run: |
          echo "Current directory:"
          pwd
          echo "Git status:"
          git status
          echo "Repository info:"
          git remote -v
          echo "Node version:"
          node --version
          echo "NPM version:"
          npm --version

      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm

      - name: Build/Release Electron app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: electron-builder
        run: |
          cd electron
          npm run build
          npm run dist

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-artifacts
          path: |
            electron/release/*.exe
            electron/release/*.dmg
            electron/release/*.AppImage
            electron/release/*.snap
            electron/release/*.deb
            electron/release/*.rpm